# Generated by Django 5.0.6 on 2024-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_room', '0002_remove_room_creator_remove_room_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pictureURL',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXV1enkTapX92ottfs5NAiaMqI66nB_NV_KA&s'),
        ),
    ]
