# Generated by Django 5.0.6 on 2024-06-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_room', '0004_alter_room_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
