# Generated by Django 5.0.6 on 2024-06-11 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_room', '0005_room_is_started'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_state', models.IntegerField(default=0)),
                ('player1_chips', models.IntegerField(default=0)),
                ('player2_chips', models.IntegerField(default=0)),
                ('player1_get_shot', models.IntegerField(default=0)),
                ('player2_get_shot', models.IntegerField(default=0)),
                ('player1_slots', models.CharField(default='0,0,0', max_length=255)),
                ('player2_slots', models.CharField(default='0,0,0', max_length=255)),
                ('bullets_position', models.CharField(default='0,0,0,0,0,0', max_length=255)),
                ('chips_in_table', models.IntegerField(default=0)),
                ('bullets_remains', models.IntegerField(default=0)),
                ('current_position', models.IntegerField(default=0)),
                ('current_round', models.IntegerField(default=0)),
                ('current_passes', models.IntegerField(default=0)),
                ('current_turn', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='a_room.room')),
            ],
        ),
    ]
