# Generated by Django 5.0.6 on 2024-06-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
